<h2>List Actor</h2>
<?php
/** @var  $block Magenest\Movie\Block\ActorTable */
$actors = $block ->getAllActors(); ?>
<table>
    <thead>
    <tr>
        <th><?php echo __('ID') ?></th>
        <th><?php echo __('Actor Name') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($actors->getData() as $actor):?>
        <tr>
            <td><?php echo $actor['actor_id'] ?></td>
            <td><?php echo $actor['name'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

